import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ['cyrillic'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <Head>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap');
        </style>
      </Head>
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  );
}
